AWSTemplateFormatVersion: 2010-09-09
Transform: "AWS::Serverless-2016-10-31"
Description: P1

Resources:
  photosalbumb2:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: photosalbumb2

  photosalbumb1:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: photosalbumb1

  IndexPhotosLF1:
    Type: "AWS::Serverless::Function"
    Properties:
      FunctionName: IndexPhotosLF1
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      CodeUri: ./LF1
      Description: LF1
      MemorySize: 128
      Timeout: 30
      Role: "arn:aws:iam::353077126427:role/service-role/LF1-index-photos-role-leftbx4t"
      Environment:
        Variables:
          Region: us-east-1
      Layers: [arn:aws:lambda:us-east-1:353077126427:layer:Requests:2]
      Events:
        S3Event:
          Type: S3
          Properties:
            Bucket: !Ref photosalbumb2
            Events: s3:ObjectCreated:Put

  SearchPhotosLF2:
    Type: "AWS::Serverless::Function"
    Properties:
      FunctionName: SearchPhotosLF2
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      CodeUri: ./LF2
      Description: LF2
      MemorySize: 128
      Timeout: 30
      Role: "arn:aws:iam::353077126427:role/service-role/LF2-search-photos-role-eev8yaaw"
      Layers: [arn:aws:lambda:us-east-1:353077126427:layer:Requests:2]
      Environment:
        Variables:
          Region: us-east-1

  RestApiPhotoAlbum:
    Type: AWS::ApiGateway::RestApi
    Properties:
      BodyS3Location:
        Bucket: b3-photos-album
        Key: "ApiPhotoAlbum-dev-swagger.yaml"
      Description: "Rest api having search photos and upload photos methods."
      Name: RestApiPhotoAlbum
      EndpointConfiguration:
        Types:
          - "REGIONAL"

  PermissionForAPIToLF2:
    Type: "AWS::Lambda::Permission"
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !GetAtt SearchPhotosLF2.Arn
      Principal: apigateway.amazonaws.com
      SourceAccount: !Ref "AWS::AccountId"
      SourceArn: !Join
        - ""
        - - "arn:aws:apigateway:us-east-1::/restapis/"
          - !Ref RestApiPhotoAlbum
          - "/resources/*/methods/GET"

  # ApiGatewayResource:
  # Type: AWS::ApiGateway::Resource
  # Properties:
  #   ParentId: !GetAtt RestApiPhotoAlbum.RootResourceId
  #   PathPart: 'lambda'
  #   RestApiId: !Ref RestApiPhotoAlbum

  # ApiGatewayMethod:
  #   Type: AWS::ApiGateway::Method
  #   Properties:
  #     HttpMethod:
  #     Integration:
  #       Type: AWS
  #       Uri: arn:aws:iam::353077126427:role/API_S3-Access
