AWSTemplateFormatVersion: 2010-09-09
Transform: "AWS::Serverless-2016-10-31"
Description: P1

Resources:
  A2S1:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: photos-album-b2
  A3L1:
    Type: "AWS::Serverless::Function"
    Properties:
      FunctionName: index-photos-lf1
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      CodeUri: ./LF1
      Description: LF1
      MemorySize: 128
      Timeout: 30
      Role: "arn:aws:iam::353077126427:role/service-role/LF1-index-photos-role-leftbx4t"
      Environment:
        Variables:
          Region: us-east-1
      Layers: [arn:aws:lambda:us-east-1:353077126427:layer:Requests:2]
      Events:
        S3Event:
          Type: S3
          Properties:
            Bucket:
              Ref: photos-album-b2
            Events: s3:ObjectCreated:Put

  A3L2:
    Type: "AWS::Serverless::Function"
    Properties:
      FunctionName: search-photos-lf2
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      CodeUri: ./LF2
      Description: LF2
      MemorySize: 128
      Timeout: 30
      Role: "arn:aws:iam::353077126427:role/service-role/LF2-search-photos-role-eev8yaaw"
      Environment:
        Variables:
          Region: us-east-1
