AWSTemplateFormatVersion: 2010-09-09
Transform: "AWS::Serverless-2016-10-31"
Description: P1

Resources:
  A3L2:
    Type: "AWS::Serverless::Function"
    Properties:
      FunctionName: LF1-index-photos
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      CodeUri: ./LF2
      Description: LF2
      MemorySize: 128
      Timeout: 30
      Role: "arn:aws:iam::353077126427:role/service-role/LF2-search-photos-role-eev8yaaw"
      Events:
        getAZsAPI:
          Type: Api
          Properties:
            Path: /search
            Method: post
      Environment:
        Variables:
          REGION: us-east-1

  A3L1:
    Type: "AWS::Serverless::Function"
    Properties:
      FunctionName: LF2-search-photos
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      CodeUri: ./LF1
      Description: LF1
      MemorySize: 128
      Timeout: 30
      Role: "arn:aws:iam::353077126427:role/service-role/LF1-index-photos-role-leftbx4t"
      Environment:
        Variables:
          REGION: us-east-1

  ElasticsearchDomain:
    Type: "AWS::Elasticsearch::Domain"
    Properties:
      DomainName: "photo-es"
      ElasticsearchVersion: "5.1"
      ElasticsearchClusterConfig:
        DedicatedMasterEnabled: "false"
        InstanceCount: "2"
        ZoneAwarenessEnabled: "true"
        InstanceType: "t2.small.elasticsearch"
      EBSOptions:
        EBSEnabled: true
        Iops: 0
        VolumeSize: 10
        VolumeType: "gp2"
      SnapshotOptions:
        AutomatedSnapshotStartHour: "0"
      AccessPolicies:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS: "*"
            Action: "es:*"
            Resource: "arn:aws:es:us-east-1:353077126427:domain/photos/*"
      AdvancedOptions:
        rest.action.multi.allow_explicit_index: "true"
