AWSTemplateFormatVersion: 2010-09-09
Transform: 'AWS::Serverless-2016-10-31'
Description: P1

Resources:
  A3b1website:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: "a3b1website"

  A3b2photostore:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: "a3b2photostore" 

  A3L2:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: A3L2
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      CodeUri: ./LF2
      Description: LF2
      MemorySize: 128
      Timeout: 30
      Role: 'arn:aws:iam::098015424271:role/service-role/LF2-role-bhscurau'
      Events:
        getAZsAPI:
          Type: Api
          Properties:
            Path: /search
            Method: post
      Environment:
        Variables:
          REGION: us-east-1

  A3L1:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: A3L1
      Handler: lambda_function.lambda_handler
      Runtime: python3.7
      CodeUri: ./LF1
      Description: LF1
      MemorySize: 128
      Timeout: 30
      Role: 'arn:aws:iam::098015424271:role/service-role/LF1_index_photos-role-d7wf3odh'
      Environment:
        Variables:
          REGION: us-east-1

  A3L3:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: A3L3
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      CodeUri: ./lambda_function_3.py
      Description: LF3
      MemorySize: 128
      Timeout: 30
      Role: 'arn:aws:iam::098015424271:role/service-role/upload_to_s3-role-9x78khho'
      Events:
        getAZsAPI:
          Type: Api
          Properties:
            Path: /uploadimage
            Method: put
      Environment:
        Variables:
          REGION: us-east-1
      
  ElasticsearchDomain:
    Type: 'AWS::Elasticsearch::Domain'
    Properties:
      DomainName: "photo-es"
      ElasticsearchVersion: '7.4'
      ElasticsearchClusterConfig:
        DedicatedMasterEnabled: 'false'
        InstanceCount: '2'
        ZoneAwarenessEnabled: 'true'
        InstanceType: "t2.small.elasticsearch"
      EBSOptions:
        EBSEnabled: true
        Iops: 0
        VolumeSize: 10
        VolumeType: "gp2"
      SnapshotOptions:
        AutomatedSnapshotStartHour: '0'
      AccessPolicies:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS: '*'
            Action: 'es:*'
            Resource: 'arn:aws:es:us-east-1:098015424271:domain/photos/*'
      AdvancedOptions:
        rest.action.multi.allow_explicit_index: "true"
