AWSTemplateFormatVersion: '2010-09-09'
Description: AWS S3 Cloud Formation
Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: PublicRead
      BucketName: b1-photos-album
      WebsiteConfiguration:
        IndexDocument: index.html
    DeletionPolicy: Retain
Outputs:
  WebsiteURL:
    Value: !GetAtt
      - S3Bucket : b1-photos-album
      - WebsiteURL : http://b1-photos-album.s3-website-us-east-1.amazonaws.com
    Description: URL for website hosted on S3
  S3BucketSecureURL:
    Value: !Join
      - ''
			- - 'https://'
        - !GetAtt
					- S3Bucket
					- DomainName
    Description: Name of S3 bucket to hold website content